---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http-metrics
  - port: 80
    name: http-service
  selector:
    app: grafana