apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: retrieval
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: retrieval
  namespace: cortex-monitoring-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: retrieval
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: retrieval
subjects:
- kind: ServiceAccount
  name: retrieval
  namespace: cortex-monitoring-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval
  labels:
    app: retrieval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrieval
  template:
    metadata:
      labels:
        app: retrieval
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "9090"
    spec:
      serviceAccountName: retrieval
      containers:
      - name: retrieval
        image: prom/prometheus:v2.27.1
        imagePullPolicy: IfNotPresent
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.retention.time=6h
        - --storage.tsdb.retention.size=10GB
        ports:
        - containerPort: 9090
          name: http-metrics
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: retrieval-config